apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-mysql-secret
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ default (include "woocommerce-store.randomPassword" .) .Values.mysql.rootPassword | b64enc | quote }}
  mysql-password: {{ default (include "woocommerce-store.randomPassword" .) .Values.mysql.password | b64enc | quote }}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}
  mysql-user: {{ .Values.mysql.user | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce-store.fullname" . }}-wordpress-secret
  labels:
    {{- include "woocommerce-store.labels" . | nindent 4 }}
type: Opaque
data:
  wordpress-admin-user: {{ .Values.wordpress.adminUser | b64enc | quote }}
  wordpress-admin-password: {{ default (include "woocommerce-store.randomPassword" .) .Values.wordpress.adminPassword | b64enc | quote }}
  wordpress-admin-email: {{ .Values.wordpress.adminEmail | b64enc | quote }}
